### ISSUE TITLE
Admin: Niceties

### ISSUE THREAD

**Issue by draymond63** [uwblueprint/rowan-house#117]
## Description
A miscellaneous pile of things to do for the admin flows.

## Goals
- [ ] User search bar shouldn't lose focus on match
- [ ] Fix 'Jane Doe' and sign out button in dashboard sidebar
    Note: the sign out button logic needs to be fixed so that the button only needs to be clicked once (currently, the starter-code button needs to be clicked twice).
- [ ] Add a `/logout` page which has the same functionality as the logout button.

#### Search bar losing focus
Try forcing focus back to the input on match?
#### Sign out button
Authenticated user should be cleared always, not just on error. This way it will be cleared on signout rather than after clicking twice.

An easy way to do this would be to make a new endpoint, `/logout`, and redirect the user to that endpoint when they click the Signout button. That endpoint can do the work of clearing localStorage and sending them to the login page again.

**Comment by e-wai** [comment]
+ No email validation at the moment on front-end side

**Comment by jfdoming** [comment]
Prioritizing this issue as it blocks the learner side of things (people need to be able to sign out and the only working sign-out button is currently on the Default page which needs to be replaced).
