### ISSUE TITLE
Verify route: resend verification email

### ISSUE THREAD

**Issue by jfdoming** [uwblueprint/rowan-house#139]
# Goals

- [ ] Users should be able to click a "resend verification email" button on the `/verify` page, and receive a new email with a verification link.

**Comment by mslwang** [comment]
What would the user flow be for this by the way? After they click on it, do they get redirected to a page that says "verification email re-sent" then on reload they go back to the original page? Then if they try to click it again in a certain time, have them rate limited somehow? I feel like that's the normal user flow with that.
