### ISSUE TITLE
Component: Heading

### ISSUE THREAD

**Issue by jfdoming** [uwblueprint/rowan-house#187]
## Summary
The header component will allow RHS to deliniate sections of their lesson. The header will show any text specified by RHS, and can be shown in a range of sizes. There will be four sizing options:

Heading 1: 32px
Heading 2: 24px
Heading 3: 20px
Heading 4: 16px

## Designs
![image.png](https://images.zenhubusercontent.com/6053e4ca8db077e41d15aa4a/814057a3-470f-43b8-85be-c2b8e2196355)
The heading will be left-aligned within the lesson. 

### Editing
![image.png](https://images.zenhubusercontent.com/6053e4ca8db077e41d15aa4a/cfc95dcd-b825-4da7-b0cc-b3b03f5ab9f7)
![image.png](https://images.zenhubusercontent.com/6053e4ca8db077e41d15aa4a/dc99e453-d64f-4a27-90b0-5990f7c693dd)
*Edit modal Designs*

The two main pieces of information the admin can edit are the display text and the heading type. The text can be typed into the textbox as shown in the designs. The heading is selectable via a dropdown within the modal. 

There are four options (H1-4), all showing their respective size within the dropdown. Show `Heading X: font size` and the preview section as shown in the designs.

### Notes
- If there is no text typed out, show the heading name in the Preview (e.g. "Heading 1")

## Implementation
You can use standard components for all the fields. Don't forget to validate the required fields!
Note: The designs show a select component where each element has different sizes. **You can ignore this and use the default select component from ChakraUI.**

**Comment by jfdoming** [comment]
Update: Looked into whether this is possible: it _will_ be, but isn't atm. There's an [open PR](https://github.com/chakra-ui/chakra-ui/pull/6241) for Chakra UI which was opened 11 days ago. Maybe we can do a v2 of this component.

**Comment by jfdoming** [comment]
Second update: After a more thorough investigation, this can be done relatively easily with [chakra-react-select](https://github.com/csandman/chakra-react-select) and the `getOptionValue` prop, rendering with the Chakra `Heading` component.

**Comment by jfdoming** [comment]
Third update: For simplicity, we'll stick with the default `Select` component.

**Comment by smilesthesad** [comment]
The option values cannot be styled right now, so cannot do following
<img width="235" alt="image" src="https://user-images.githubusercontent.com/36215359/184048371-a1508fde-3861-4d36-a31d-678a1798a9ee.png">

As a workaround, just putting brackets around px values instead
<img width="576" alt="image" src="https://user-images.githubusercontent.com/36215359/184048393-8e0cab82-f95a-4603-bf9c-c368c5ad7634.png">
