### ISSUE TITLE
Login Flow: Misc Improvements

### ISSUE THREAD

**Issue by jfdoming** [uwblueprint/rowan-house#190]
## Summary
Small tweaks to the login flow to make it have a nicer user experience.
### Login page
- [x] Auto-focus the sign-in input on page load.
- [x] Disable the "Continue" button until the user enters something in the email field.
- [x] Disable the "Login" button until the user enters something in the password field.
- [x] If the login fails for some reason, display a generic error message.
- [x] Use `FormLabel`s for the login form instead of the current manual labelling. (Make sure the spacing doesn't change.)
- [x] Fix autofill being broken on this page.
- [x] Enter should submit each field (i.e., press enter on email -> validate and take you to password; press enter on password -> validate and submit)
### Signup page
- [x] Auto-focus the "Name" field on page load.
- [x] Fields should not be in an error state unless the form is submitted with the field empty.
- [x] Form error messages should appear underneath the corresponding field rather than at the bottom of the form.
- [x] Both password fields should not autocomplete passwords.
- [x] Other form fields should have autocomplete enabled.
### Login page
You'll need to use a [ref](https://reactjs.org/docs/hooks-reference.html#useref) to get a handle to the input in order to auto-focus it. You can put the focus call itself within a `useEffect` hook with empty dependencies.

You can use [FormLabel](https://v0.chakra-ui.com/formcontrol) for form labels.

To fix autofill, both the email and password fields need to be on the page at all times. You can hide one or the other manually using styling (`display="none"`) rather than conditional rendering. Be sure to leave a comment indicating why we're doing things this way!
### Signup page
The password fields can use `autocomplete="new-password"` as a prop. Other form fields can use the appropriate `autocomplete` attributes, e.g., `autocomplete="given-name"` for the First Name field. See [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) for a full list.

**Comment by draymond63** [comment]
In the event of an error logging in, the following visual should be shown:
![image.png](https://images.zenhubusercontent.com/6053e4ca8db077e41d15aa4a/ac269af5-de34-4a30-ac6a-03c640a7995c)

Once the user starts editing the password or goes back to the email section, the error visuals will be removed.
