### ISSUE TITLE
Course Overview: Course Details

### ISSUE THREAD

**Issue by jfdoming** [uwblueprint/rowan-house#201]
# Summary
The course overview page should display information about the current course.
# Designs
![image](https://user-images.githubusercontent.com/9922514/178134322-0ca81623-bf0e-4b16-b432-98dfcebc115c.png)
[Figma](https://www.figma.com/file/hVyZkprXKN6myQuaIvRqfr/Learner-Views?node-id=249%3A5464)
# Goals
- [ ] Breadcrumb at top of course details
- [ ] Basic course info can be displayed (e.g., title, description, # of modules)
# Implementation
See [here](https://chakra-ui.com/docs/components/breadcrumb/usage#using-an-icon-as-the-separator) for the breadcrumb. You can fetch course info from the `GET_COURSE` endpoint based on the ID from the URL.

**Comment by draymond63** [comment]
See #193 as I wrote a bit about this there. Feel free to copy and paste it into here.
