### ISSUE TITLE
Lesson Viewer: Sidebar

### ISSUE THREAD

**Issue by jfdoming** [uwblueprint/rowan-house#218]
## Summary
We want to update the lessons within the sidebar based on whether a user has completed them.

## Goals
- [x] Fetch data from the GQL `GET_LESSON_PROGRESS` endpoint.
- [x] Set the focused course based on the lesson progress.
- [x] Update the lesson's icon and disabled state based on the progress to reflect the designs (locked -> up next -> completed).
- [x] Add a tooltip to disabled lessons

## Designs
![image](https://user-images.githubusercontent.com/9922514/182006080-b801eb05-5a28-4e5b-8c5f-c0ff15ae39b2.png)
Example of a disabled lesson, with tooltip:
![image](https://user-images.githubusercontent.com/9922514/182006237-d839880b-a89f-4b53-9acd-639842381ef7.png)

https://www.figma.com/file/hVyZkprXKN6myQuaIvRqfr/Learner-Views?node-id=220%3A2792

## Implementation
See above. You can use the [`Tooltip`](https://chakra-ui.com/docs/components/tooltip) component with the `hasArrow` and [`placement`](https://chakra-ui.com/docs/components/tooltip#placement) props to match the design.

**Comment by smilesthesad** [comment]
https://github.com/uwblueprint/rowan-house/pull/237

**Comment by smilesthesad** [comment]
https://github.com/uwblueprint/rowan-house/pull/237
