### ISSUE TITLE
Landing Page: Course Block Component

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/rowan-house#62]
## Summary
- Contains major information about a course (title, description, private/public status tag)
- Contains a list of module components (these components are implemented in a different ticket)
- Contains a drop down menu with buttons to edit or delete the course
- Contains a button to create a new module
## Goals
- [x] I am able to see the course title, description, and privacy tag
- [ ] I am able to add an unlimited number of modules to the course
- [x] I am able to click on the dropdown menu and be shown options to edit details or delete a course
- [x] Frontend matches closely with the designs
## Design Behaviour
- [Figma](https://www.figma.com/file/Dimm13cjrpYU5LkcrV6VxF/Course-Editor?node-id=627%3A2809)
- Course descriptions will have a character limit, so no need to display overflow 
- Modules will overflow on the same page automatically 
- Clicking the three dots will bring out a dropdown menu to select options from. Selecting either edit or delete will pop up a modal for the action (implemented in a different ticket)
- Clicking the create module button will pop up a modal (also a different ticket) 
![image](https://user-images.githubusercontent.com/50289930/155444111-84756615-fb46-40e9-bdd8-d99442a47332.png)
![image](https://user-images.githubusercontent.com/50289930/155444140-940cb4b5-66ba-487a-aabb-0ba69b0cef54.png)
![image](https://user-images.githubusercontent.com/50289930/155444189-fcefa705-b334-434a-b612-e8e62de20951.png)
## Implementation
This component is mostly visual, taken in the data through props from its parent. The layout should be a VStack, with a Grid for the iterated modules. The module preview will be created in another ticket

### Interactions
The "more-options" button (ellipsis) should expand a menu, but none of the options in the menu should work (we will save that for later). As well, the "Create Module" button should exist, but it again shouldn't do anything.

**Comment by e-wai** [comment]
No GraphQL, but other items addressed in https://github.com/uwblueprint/rowan-house/pull/95

**Comment by e-wai** [comment]
@y2kwak I could be wrong, but is the "Create new module" ticket scoped in your work?
