### ISSUE TITLE
Landing Page: Module Component

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/rowan-house#63]
## Summary
- Show a brief overview of a module, including an image, title, and (optional) draft tag
- Have a dropdown menu to edit and delete the module
## Goals
- [x] I have an individual module component that can easily be plugged into a list on other module components within a course block
- [x] My module component displays the module's title and photo
- [x] My module can have a draft tag
- [x] I can use the drop down to click the edit and delete module buttons
- [x] The frontend closely reflects the designs
## Design Behaviour
- [Figma](https://www.figma.com/file/Dimm13cjrpYU5LkcrV6VxF/Course-Editor?node-id=626%3A2808)
- Clicking a button in the dropdown menu opens up a modal (to be implemented in a different ticket)
- Multiple module components will be side by side in a course
- Draft tags are removed if the course is published (and added if its converted back to draft)
- Clicking anywhere on the module other than the 3 dots redirects a user to the module editor (maybe just have an empty redirect for now)
![image](https://user-images.githubusercontent.com/50289930/155445873-c1a07af6-979f-4e12-8238-ac7fd92cfff4.png)
![image](https://user-images.githubusercontent.com/50289930/155445891-55b2c532-d59b-4e19-b093-397595f7b2ee.png)

## Implementation
Don't worry about the buttons in the kebab menu doing anything yet (we will add modals later). Other than that, render the props as shown :)

**Comment by e-wai** [comment]
Think https://github.com/uwblueprint/rowan-house/pull/95 closes this too
