### ISSUE TITLE
Update course API to include modules

### ISSUE THREAD

**Issue by draymond63** [uwblueprint/rowan-house#98]
## Summary
The `courses` query should return different things based on who is requesting the courses. It currently does this, but it is now out of date. The published attribute is now a part of the module, not the course document. In addition to this, the `course` query should also filter in a similar way.

The `course` query should filter in the following way:
 - Users can see published modules in public courses
 - Staff can see all published modules in any courses (private and non-private)
 - Admins can see all modules in all courses

For more information regarding the API, see [here](https://www.notion.so/uwblueprintexecs/Read-All-Available-Courses-89a7fd55b3344bd493d6fdfc05c4d2c4).

## Goals
- [x] Update `courses` API to filter modules based on their `published` attribute
- [x] Update the `course` API to filter base on user credentials (same way the `courses` API does)
  - If a learner requests a private course, return an "ID unknown" error
- [x] Remove published attribute from course interfaces in frontend and backend

## Implementation
There is a currently implementation for filtration based on attributes for the `courses` API. This will have to be slightly modified, but will serve a good reference to build off of.

**Comment by e-wai** [comment]
Think this is good 👍
